from tools.file_tools import write_file
from rag import store_project_files

def file_writer_agent(state):
    """
    Write files generated by the Coder Agent into the project directory.

    Responsibilities:
    - Write every generated/modified file.
    - Capture file-level failures without crashing the graph.
    - Store successfully written files in ChromaDB.
    - Preserve previous errors in LangGraph state.
    """
    project_id = state["project_id"]
    files = state.get("files", {})
    previous_errors = state.get("errors", [])

    print("WRITING_FILES")

    if not files:
        print("No files generated by coder.")
        return {
            "status": "FILE_WRITING_FAILED",
            "errors": previous_errors + [
                "Coder Agent did not generate any files."
            ],
        }

    written_files = {}
    write_errors = []

    # --------------------------------------------------
    # WRITE GENERATED FILES
    # --------------------------------------------------
    for file_path, content in files.items():
        try:
            if not file_path or not isinstance(file_path, str):
                write_errors.append(f"Invalid file path: {file_path}")
                continue

            if not isinstance(content, str):
                write_errors.append(f"Invalid content for file: {file_path}")
                continue

            result = write_file(project_id, file_path, content)
            written_files[file_path] = content

            print(f"  Created/Updated: {result}")

        except Exception as e:
            error_message = f"Failed to write '{file_path}': {str(e)}"
            write_errors.append(error_message)
            print(f"  ERROR: {error_message}")

    # --------------------------------------------------
    # STORE SUCCESSFULLY WRITTEN FILES IN RAG
    # --------------------------------------------------
    if written_files:
        try:
            store_project_files(project_id, written_files)
            print(f"  Stored {len(written_files)} file(s) in ChromaDB memory")
        except Exception as e:
            # RAG failure should not make the actual
            # file-writing operation fail.
            print(f"  WARNING: Failed to store files in ChromaDB: {e}")

    # --------------------------------------------------
    # DETERMINE FINAL STATUS
    # --------------------------------------------------
    all_errors = previous_errors + write_errors

    if write_errors:
        status = "FILE_WRITING_FAILED"
        print(f"FILE_WRITING_FAILED ({len(write_errors)} error(s))")
    else:
        status = "FILES_WRITTEN"
        print(f"FILES_WRITTEN ({len(written_files)} file(s))")

    # --------------------------------------------------
    # RETURN ONLY CHANGED STATE
    # --------------------------------------------------
    return { 
        "status": status, "errors": all_errors,
          }